#include "config.h"
#include <string.h>
#include <generic.h>
#include "slot.h"
#define _UPWATCH
#include "probe.h"

#ifdef DMALLOC
#include "dmalloc.h"
#endif

//*******************************************************************
// GET THE INFO FROM THE XML FILE
// Caller must free the pointer it returns
//*******************************************************************
void sysstat_get_from_xml(trx *t)
{
  struct sysstat_result *res = (struct sysstat_result *)t->res;

  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "loadavg")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->loadavg = xmlNodeListGetFloat(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "user")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->user = xmlNodeListGetInt(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "system")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->system = xmlNodeListGetInt(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "idle")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->idle = xmlNodeListGetInt(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "swapin")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->swapin = xmlNodeListGetInt(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "swapout")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->swapout = xmlNodeListGetInt(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "blockin")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->blockin = xmlNodeListGetInt(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "blockout")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->blockout = xmlNodeListGetInt(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "swapped")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->swapped = xmlNodeListGetInt(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "free")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->free = xmlNodeListGetInt(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "buffered")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->buffered = xmlNodeListGetInt(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "cached")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->cached = xmlNodeListGetInt(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "used")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->used = xmlNodeListGetInt(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
  if ((!xmlStrcmp(t->cur->name, (const xmlChar *) "systemp")) && (xmlNsEqual(t->cur->ns, t->ns))) {
    res->systemp = xmlNodeListGetInt(t->doc, t->cur->xmlChildrenNode, 1);
    return;
  }
}

//*******************************************************************
// find the real probeid from the server id
// get it from the cache. if there but too old: delete
//*******************************************************************
void *sysstat_get_def(trx *t, int create)
{ 
  struct probe_def *def;
  struct sysstat_result *res = (struct sysstat_result *)t->res;
  dbi_result result;
  time_t now = time(NULL);

  if (res->color == STAT_PURPLE) { // generated by uw_purple, which knows the probe id but not the serverid
    result = db_query(t->probe->db, 0,
                      "select server from pr_%s_def where id = '%u'", res->name, res->probeid);
    if (!result) return(NULL);

    if (dbi_result_get_numrows(result) == 0) {
      LOG(LOG_NOTICE, "%s:%u@%s: %s def %u not found", 
          res->realm, res->stattime, t->fromhost, res->name, res->probeid);
      dbi_result_free(result);
      delete_pr_status(t, res->probeid);
      return(NULL);
    }
    dbi_result_next_row(result);
    res->server = dbi_result_get_uint(result, "server");
    dbi_result_free(result);
  }

  def = g_hash_table_lookup(t->probe->cache, &res->server);
  if (def && def->stamp < now - (120 + uw_rand(240))) { // older then 2 - 6 minutes?
     g_hash_table_remove(t->probe->cache, &res->server);
     def = NULL;
  }
  // if not there retrieve from database and insert in hash
  if (def == NULL) {
    def = g_malloc0(t->probe->def_size);
    def->stamp = time(NULL);
    strcpy(def->hide, "no");
    def->server = res->server;
    
    result = db_query(t->probe->db, 0,
                      "select id, yellow, red, contact, hide, email, sms, delay, pgroup "
                      "from   pr_%s_def "
                      "where  server = '%u'", res->name, res->server);
    if (!result) return(NULL);

    if (dbi_result_get_numrows(result) == 0) { // DEF RECORD NOT FOUND
      dbi_result_free(result);
      if (!create) {
        LOG(LOG_NOTICE, "%s:%u@%s: pr_%s_def for server %u not found and not trusted - skipped", 
                         res->realm, res->stattime, t->fromhost, res->name, def->server);
        return(NULL);
      }
      result = db_query(t->probe->db, 0,
                        "insert into pr_%s_def set server = '%d', "
                        "        ipaddress = '%s', description = '%s'", 
                        res->name, res->server, t->res->ipaddress ? t->res->ipaddress : "127.0.0.1", 
                        t->fromhost ? t->fromhost : "automatically added");
      dbi_result_free(result);
      if (dbi_result_get_numrows_affected(t->probe->db) == 0) { // nothing was actually inserted
        const char *errmsg;
        dbi_conn_error(t->probe->db, &errmsg);
        LOG(LOG_NOTICE, "%s:%u@%s: insert missing pr_%s_def id %u: %s", 
                         res->realm, res->stattime, t->fromhost,
                         res->name, def->probeid, errmsg);
      }
      result = db_query(t->probe->db, 0,
                        "select id, yellow, red, contact, hide, email, sms, delay, pgroup "
                        "from   pr_%s_def "
                        "where  server = '%u'", res->name, res->server);
      if (!result) return(NULL);
    }
    if (dbi_result_get_numrows(result) == 0) {
      LOG(LOG_NOTICE, "%s:%u@%s: no pr_%s_def found for server %u - skipped",
          res->realm, res->stattime, t->fromhost, res->name, res->server);
      dbi_result_free(result);
      g_free(def);
      return(NULL);
    }
    dbi_result_next_row(result);

    def->probeid = dbi_result_get_uint(result, "id");
    def->yellow = dbi_result_get_float(result, "yellow");
    def->red = dbi_result_get_float(result, "red");
    def->contact = dbi_result_get_uint(result, "contact");
    strcpy(def->hide, dbi_result_get_string(result, "hide"));
    strcpy(def->email, dbi_result_get_string(result, "email"));
    strcpy(def->sms, dbi_result_get_string(result, "sms"));
    def->delay = dbi_result_get_uint(result, "delay");
    def->pgroup = dbi_result_get_uint(result, "pgroup");
    dbi_result_free(result);

    result = db_query(t->probe->db, 0,
                      "select color "
                      "from   pr_status "
                      "where  class = '%d' and probe = '%d'", t->probe->class, def->probeid);
    if (result) {
      if (dbi_result_get_numrows(result) == 0) {
        LOG(LOG_NOTICE, "%s:%u@%s: pr_status record for %s id %u not found",
           res->realm, res->stattime, t->fromhost, res->name, def->probeid);
      } else {
        dbi_result_next_row(result);
        def->color   = dbi_result_get_uint(result, "color");
        dbi_result_free(result);
      }
    }
    if (!def->color) def->color = res->color;

    result = db_query(t->probe->db, 0,
                      "select stattime from pr_%s_raw use index(probstat) "
                      "where probe = '%u' order by stattime desc limit 1",
                       res->name, def->probeid);
    if (result) {
      if (dbi_result_get_numrows(result) > 0) {
        dbi_result_next_row(result);
        def->newest  = dbi_result_get_uint(result, "stattime");
        dbi_result_free(result);
      }
    }

    g_hash_table_insert(t->probe->cache, guintdup(res->server), def);
  }
  res->probeid = def->probeid;
  return(def);
}   

//*******************************************************************
// Adjust the result. In this case this means:
// don't trust the color we receive from the probe
//*******************************************************************
void sysstat_adjust_result(trx *t)
{ 
  struct sysstat_result *res = (struct sysstat_result *)t->res;

  if (res->color != STAT_PURPLE) {
    char buffer[10];

    res->color = STAT_GREEN;
    if (res->loadavg > t->def->yellow) res->color = STAT_YELLOW;
    if (res->loadavg > t->def->red) res->color = STAT_RED;
    sprintf(buffer, "%u", res->color);
    set_result_value(t, "color", buffer);
  }
}
