.TH get_load_stats 3 $Date: 2003/12/04 18:59:17 $ i\-scream 
.SH NAME
get_load_stats \- get system load
.SH SYNOPSIS
.nf
#include <statgrab.h>
.fi
.sp 1
.PP
load_stat_t *\fIget_load_stats\fR(void);
.SH DESCRIPTION
This call returns a pointer to a static buffer of
load_stat_t.
.PP
On most systems this function is just a wrapper to the
getloadavg system call.
.SH RETURN\ VALUES
The structure returned is of type
load_stat_t.
.PP
.nf

typedef struct{
	double min1;
	double min5;
	double min15;
}load_stat_t;
    
.fi
.TP 
min1
The load average over 1 minute.
.TP 
min5
The load average over 5 minutes.
.TP 
min15
The load average over 15 minutes.
.SH SEE\ ALSO
\fBstatgrab\fR(3)
.SH WEBSITE
http://www.i\-scream.org
