.TH get_page_stats 3 $Date: 2003/12/04 18:59:17 $ i\-scream 
.SH NAME
get_page_stats, get_page_stats_diff \- get paging statistics
.SH SYNOPSIS
.nf
#include <statgrab.h>
.fi
.sp 1
.PP
page_stat_t *\fIget_page_stats\fR(void);
.PP
page_stat_t *\fIget_page_stats_diff\fR(void);
.SH DESCRIPTION
get_page_stats and
get_page_stats_diff both return a pointer to
a static buffer of type page_stat_t.
.PP
get_page_stats will return the number of
pages the system has paged in and out since bootup.
get_page_stats_diff will return the
difference since last time it was called. If it has not been
called before, it will return
get_page_stats.
.SH RETURN\ VALUES
.nf

typedef struct{
        long long pages_pagein;
        long long pages_pageout;
        time_t systime;
}page_stat_t;
    
.fi
.TP 
pages_pagein  
The number of pages swapped into memory.
.TP 
pages_pageout  
The number of pages swapped out of memory (to swap).
.TP 
systime  
The time period over which pages_pagein
and pages_pageout were transferred.
.SH BUGS
Solaris doesn't seem to report accurately. It reports the number
of pages swapped into memory, not necessarily from swap. This
feature isn't deemed entirely reliable.
.SH SEE\ ALSO
\fBstatgrab\fR(3)
.SH WEBSITE
http://www.i\-scream.org
