.TH get_user_stats 3 $Date: 2003/12/04 18:59:17 $ i\-scream 
.SH NAME
get_user_stats \- get the current logged in users
.SH SYNOPSIS
.nf
#include <statgrab.h>
.fi
.sp 1
.PP
user_stat_t *\fIget_user_stats\fR(void);
.SH DESCRIPTION
This call returns a pointer to a static buffer of
user_stat_t.
.SH RETURN\ VALUES
The structure returned is of type
user_stat_t.
.PP
.nf

typedef struct{
        char *name_list;
        int num_entries;
}user_stat_t;
    
.fi
.TP 
name_list
A pointer to a space seperated list of the currently
logged in users.
.TP 
num_entries
The number of users currently logged in.
.SH SEE\ ALSO
\fBstatgrab\fR(3)
.SH WEBSITE
http://www.i\-scream.org
