.TH get_general_stats 3 $Date: 2003/12/04 18:59:17 $ i\-scream 
.SH NAME
get_general_stats \- get general operating system statistics
.SH SYNOPSIS
.nf
#include <statgrab.h>
.fi
.sp 1
.PP
general_stat_t *\fIget_general_stats\fR(void);
.SH DESCRIPTION
This call returns details on the operating system.
.PP
It returns a pointer to a static buffer of
general_stat_t.
.SH RETURN\ VALUES
The structure returned is of type
general_stat_t.
.PP
.nf

typedef struct{
        char *os_name;
        char *os_release;
        char *os_version;
        char *platform;
        char *hostname;
        time_t uptime;
}general_stat_t;
    
.fi
.TP 
os_name
the operating system name.
(eg. SunOS or Linux)
.TP 
os_release
the operating system release.
(eg. 5.8 or 5.9 or Solaris)
.TP 
os_version
the version level of the OS.
.TP 
platform
the hardware platform (architecture) the OS runs on.
.TP 
hostname
the name of the machine.
.TP 
uptime
the uptime of the machine in seconds.
.SH SEE\ ALSO
\fBstatgrab\fR(3)
.SH WEBSITE
http://www.i\-scream.org
