/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (uw_tnot.c)
 *  
 *  It has been AutoGen-ed  Tuesday January  6, 2004 at 11:44:46 AM CET
 *  From the definitions    uw_tnot.def
 *  and the template file   options
 */
#include "uw_tnot.h"

tSCC zCopyright[] =
       "uw_tnot copyright (c) 2002 Upwatch BV, all rights reserved";
tSCC zCopyrightNotice[] =
       "Redistribution Prohibited. Violation will be prosecuted to the maximum extent possible by applicable law.";

extern tUsageProc optionUsage;


#ifndef NULL
#  define NULL 0
#endif
#ifndef EXIT_SUCCESS
#  define  EXIT_SUCCESS 0
#endif
#ifndef EXIT_FAILURE
#  define  EXIT_FAILURE 1
#endif
/*
 *  Compress option description:
 */
tSCC    zCompressText[] =
        "XML compression factor";
tSCC    zCompress_NAME[]           = "COMPRESS";
#define zNotCompress_Pfx             NULL
#define zNotCompress_Name            NULL
tSCC    zCompress_Name[]           = "compress";
#define zCompressDefaultArg          ((tCC*)9)
#define COMPRESS_FLAGS       (OPTST_NUMERIC | OPTST_DISABLED | OPTST_INIT)

/*
 *  Spooldir option description:
 */
tSCC    zSpooldirText[] =
        "maildir-type spooldirectory for result files";
tSCC    zSpooldir_NAME[]           = "SPOOLDIR";
#define zNotSpooldir_Pfx             NULL
#define zNotSpooldir_Name            NULL
tSCC    zSpooldir_Name[]           = "spooldir";
#define SPOOLDIR_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Input option description:
 */
tSCC    zInputText[] =
        "name of queue to read from";
tSCC    zInput_NAME[]              = "INPUT";
#define zNotInput_Pfx                NULL
#define zNotInput_Name               NULL
tSCC    zInput_Name[]              = "input";
#define INPUT_FLAGS       (OPTST_STACKED | OPTST_DISABLED | OPTST_INIT)

/*
 *  Output option description:
 */
tSCC    zOutputText[] =
        "name of queue to drop results";
tSCC    zOutput_NAME[]             = "OUTPUT";
#define zNotOutput_Pfx               NULL
#define zNotOutput_Name              NULL
tSCC    zOutput_Name[]             = "output";
#define OUTPUT_FLAGS       (OPTST_STACKED | OPTST_DISABLED | OPTST_INIT)

/*
 *  Failures option description:
 */
tSCC    zFailuresText[] =
        "name of queue to store failed transactions";
tSCC    zFailures_NAME[]           = "FAILURES";
#define zNotFailures_Pfx             NULL
#define zNotFailures_Name            NULL
tSCC    zFailures_Name[]           = "failures";
#define FAILURES_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Notify option description:
 */
tSCC    zNotifyText[] =
        "name of queue to drop results with a notification on them";
tSCC    zNotify_NAME[]             = "NOTIFY";
#define zNotNotify_Pfx               NULL
#define zNotNotify_Name              NULL
tSCC    zNotify_Name[]             = "notify";
#define NOTIFY_FLAGS       (OPTST_STACKED | OPTST_DISABLED | OPTST_INIT)

/*
 *  Smtpserver option description:
 */
tSCC    zSmtpserverText[] =
        "Outgoing SMTP server";
tSCC    zSmtpserver_NAME[]         = "SMTPSERVER";
#define zNotSmtpserver_Pfx           NULL
#define zNotSmtpserver_Name          NULL
tSCC    zSmtpserver_Name[]         = "smtpserver";
tSCC    zSmtpserverDefaultArg[]      = "localhost";
#define SMTPSERVER_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Smtpserverport option description:
 */
tSCC    zSmtpserverportText[] =
        "Outgoing SMTP server port";
tSCC    zSmtpserverport_NAME[]     = "SMTPSERVERPORT";
#define zNotSmtpserverport_Pfx       NULL
#define zNotSmtpserverport_Name      NULL
tSCC    zSmtpserverport_Name[]     = "smtpserverport";
#define zSmtpserverportDefaultArg    ((tCC*)25)
#define SMTPSERVERPORT_FLAGS       (OPTST_NUMERIC | OPTST_DISABLED | OPTST_INIT)

/*
 *  From_Email option description:
 */
tSCC    zFrom_EmailText[] =
        "Email address for outgoing messages";
tSCC    zFrom_Email_NAME[]         = "FROM_EMAIL";
#define zNotFrom_Email_Pfx           NULL
#define zNotFrom_Email_Name          NULL
tSCC    zFrom_Email_Name[]         = "from-email";
tSCC    zFrom_EmailDefaultArg[]      = "beheer@netland.nl";
#define FROM_EMAIL_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  From_Name option description:
 */
tSCC    zFrom_NameText[] =
        "Email name for outgoing messages";
tSCC    zFrom_Name_NAME[]          = "FROM_NAME";
#define zNotFrom_Name_Pfx            NULL
#define zNotFrom_Name_Name           NULL
tSCC    zFrom_Name_Name[]          = "from-name";
tSCC    zFrom_NameDefaultArg[]       = "CMS Netland Internet Services BV";
#define FROM_NAME_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Copy option description:
 */
tSCC    zCopyText[] =
        "file to copy all transactions to";
tSCC    zCopy_NAME[]               = "COPY";
#define zNotCopy_Pfx                 NULL
#define zNotCopy_Name                NULL
tSCC    zCopy_Name[]               = "copy";
#define COPY_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Trust option description:
 */
tSCC    zTrustText[] =
        "create definition record for this probe if not found";
tSCC    zTrust_NAME[]              = "TRUST";
#define zNotTrust_Pfx                NULL
#define zNotTrust_Name               NULL
tSCC    zTrust_Name[]              = "trust";
#define TRUST_FLAGS       (OPTST_STACKED | OPTST_DISABLED | OPTST_INIT)

/*
 *  Run_Queue option description:
 */
tSCC    zRun_QueueText[] =
        "Process the queue once, and then exit";
tSCC    zRun_Queue_NAME[]          = "RUN_QUEUE";
#define zNotRun_Queue_Pfx            NULL
#define zNotRun_Queue_Name           NULL
tSCC    zRun_Queue_Name[]          = "run-queue";
#define RUN_QUEUE_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Query_Server_By_Name option description:
 */
tSCC    zQuery_Server_By_NameText[] =
        "SQL query to find the id of a server given the servername";
tSCC    zQuery_Server_By_Name_NAME[] = "QUERY_SERVER_BY_NAME";
#define zNotQuery_Server_By_Name_Pfx NULL
#define zNotQuery_Server_By_Name_Name NULL
tSCC    zQuery_Server_By_Name_Name[]= "query-server-by-name";
tSCC    zQuery_Server_By_NameDefaultArg[]= "select id from server where name like '%%%s%%' or names like '%%%s%%'";
#define QUERY_SERVER_BY_NAME_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Query_Server_By_Id option description:
 */
tSCC    zQuery_Server_By_IdText[] =
        "SQL query to find the name of a server given the id";
tSCC    zQuery_Server_By_Id_NAME[] = "QUERY_SERVER_BY_ID";
#define zNotQuery_Server_By_Id_Pfx   NULL
#define zNotQuery_Server_By_Id_Name  NULL
tSCC    zQuery_Server_By_Id_Name[] = "query-server-by-id";
tSCC    zQuery_Server_By_IdDefaultArg[]= "select name from server where id = '%u'";
#define QUERY_SERVER_BY_ID_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Query_Server_By_Ip option description:
 */
tSCC    zQuery_Server_By_IpText[] =
        "SQL query to find the id of a server given the ip address";
tSCC    zQuery_Server_By_Ip_NAME[] = "QUERY_SERVER_BY_IP";
#define zNotQuery_Server_By_Ip_Pfx   NULL
#define zNotQuery_Server_By_Ip_Name  NULL
tSCC    zQuery_Server_By_Ip_Name[] = "query-server-by-ip";
tSCC    zQuery_Server_By_IpDefaultArg[]= "select server.id from server, ipaddress where ipaddress.id = server.ipaddress and ipaddress.name = '%s'";
#define QUERY_SERVER_BY_IP_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Summarize option description:
 */
tSCC    zSummarizeText[] =
        "Re-summarize a named probe in a certain period";
tSCC    zSummarize_NAME[]          = "SUMMARIZE";
#define zNotSummarize_Pfx            NULL
#define zNotSummarize_Name           NULL
tSCC    zSummarize_Name[]          = "summarize";
#define SUMMARIZE_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Multi_Value_Inserts option description:
 */
tSCC    zMulti_Value_InsertsText[] =
        "combine single inserts into multi value inserts for speed";
tSCC    zMulti_Value_Inserts_NAME[] = "MULTI_VALUE_INSERTS";
#define zNotMulti_Value_Inserts_Pfx  NULL
#define zNotMulti_Value_Inserts_Name NULL
tSCC    zMulti_Value_Inserts_Name[]= "multi-value-inserts";
#define MULTI_VALUE_INSERTS_FLAGS       (OPTST_BOOLEAN | OPTST_DISABLED | OPTST_INIT)

/*
 *  Multi_Value_Cache_Size option description:
 */
tSCC    zMulti_Value_Cache_SizeText[] =
        "How many insert to combine into one";
tSCC    zMulti_Value_Cache_Size_NAME[] = "MULTI_VALUE_CACHE_SIZE";
#define zNotMulti_Value_Cache_Size_Pfx NULL
#define zNotMulti_Value_Cache_Size_Name NULL
tSCC    zMulti_Value_Cache_Size_Name[]= "multi-value-cache-size";
#define zMulti_Value_Cache_SizeDefaultArg ((tCC*)20)
#define MULTI_VALUE_CACHE_SIZE_FLAGS       (OPTST_NUMERIC | OPTST_DISABLED | OPTST_INIT)

/*
 *  Slave option description:
 */
tSCC    zSlaveText[] =
        "Force this instance to act as a slave for the given queue";
tSCC    zSlave_NAME[]              = "SLAVE";
#define zNotSlave_Pfx                NULL
#define zNotSlave_Name               NULL
tSCC    zSlave_Name[]              = "slave";
#define SLAVE_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Dbtype option description:
 */
tSCC    zDbtypeText[] =
        "Database type to use (mysql or postgresql)";
tSCC    zDbtype_NAME[]             = "DBTYPE";
#define zNotDbtype_Pfx               NULL
#define zNotDbtype_Name              NULL
tSCC    zDbtype_Name[]             = "dbtype";
tSCC    zDbtypeDefaultArg[]          = "mysql";
#define DBTYPE_FLAGS       (OPTST_MUST_SET | OPTST_DISABLED | OPTST_INIT)

/*
 *  Dbcompress option description:
 */
tSCC    zDbcompressText[] =
        "Use compression on database connection";
tSCC    zDbcompress_NAME[]         = "DBCOMPRESS";
#define zNotDbcompress_Pfx           NULL
#define zNotDbcompress_Name          NULL
tSCC    zDbcompress_Name[]         = "dbcompress";
#define zDbcompressDefaultArg        ((tCC*)1)
#define DBCOMPRESS_FLAGS       (OPTST_NUMERIC | OPTST_MUST_SET | OPTST_DISABLED | OPTST_INIT)

/*
 *  Dbhost option description:
 */
tSCC    zDbhostText[] =
        "Database host to connect to";
tSCC    zDbhost_NAME[]             = "DBHOST";
#define zNotDbhost_Pfx               NULL
#define zNotDbhost_Name              NULL
tSCC    zDbhost_Name[]             = "dbhost";
#define DBHOST_FLAGS       (OPTST_MUST_SET | OPTST_DISABLED | OPTST_INIT)

/*
 *  Dbport option description:
 */
tSCC    zDbportText[] =
        "Port number on database host";
tSCC    zDbport_NAME[]             = "DBPORT";
#define zNotDbport_Pfx               NULL
#define zNotDbport_Name              NULL
tSCC    zDbport_Name[]             = "dbport";
#define zDbportDefaultArg            ((tCC*)3306)
#define DBPORT_FLAGS       (OPTST_NUMERIC | OPTST_MUST_SET | OPTST_DISABLED | OPTST_INIT)

/*
 *  Dbname option description:
 */
tSCC    zDbnameText[] =
        "Database name to connect to";
tSCC    zDbname_NAME[]             = "DBNAME";
#define zNotDbname_Pfx               NULL
#define zNotDbname_Name              NULL
tSCC    zDbname_Name[]             = "dbname";
#define DBNAME_FLAGS       (OPTST_MUST_SET | OPTST_DISABLED | OPTST_INIT)

/*
 *  Dbuser option description:
 */
tSCC    zDbuserText[] =
        "Database user to connect as";
tSCC    zDbuser_NAME[]             = "DBUSER";
#define zNotDbuser_Pfx               NULL
#define zNotDbuser_Name              NULL
tSCC    zDbuser_Name[]             = "dbuser";
#define DBUSER_FLAGS       (OPTST_MUST_SET | OPTST_DISABLED | OPTST_INIT)

/*
 *  Dbpasswd option description:
 */
tSCC    zDbpasswdText[] =
        "Database password";
tSCC    zDbpasswd_NAME[]           = "DBPASSWD";
#define zNotDbpasswd_Pfx             NULL
#define zNotDbpasswd_Name            NULL
tSCC    zDbpasswd_Name[]           = "dbpasswd";
#define DBPASSWD_FLAGS       (OPTST_MUST_SET | OPTST_DISABLED | OPTST_INIT)

/*
 *  Server_Table_Name option description:
 */
tSCC    zServer_Table_NameText[] =
        "Name of the servertable in the database";
tSCC    zServer_Table_Name_NAME[]  = "SERVER_TABLE_NAME";
#define zNotServer_Table_Name_Pfx    NULL
#define zNotServer_Table_Name_Name   NULL
tSCC    zServer_Table_Name_Name[]  = "server-table-name";
tSCC    zServer_Table_NameDefaultArg[]= "server";
#define SERVER_TABLE_NAME_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Server_Table_Name_Field option description:
 */
tSCC    zServer_Table_Name_FieldText[] =
        "Name of the name-field in the servertable";
tSCC    zServer_Table_Name_Field_NAME[] = "SERVER_TABLE_NAME_FIELD";
#define zNotServer_Table_Name_Field_Pfx NULL
#define zNotServer_Table_Name_Field_Name NULL
tSCC    zServer_Table_Name_Field_Name[]= "server-table-name-field";
tSCC    zServer_Table_Name_FieldDefaultArg[]= "name";
#define SERVER_TABLE_NAME_FIELD_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Server_Table_Id_Field option description:
 */
tSCC    zServer_Table_Id_FieldText[] =
        "Name of the id-field in the servertable";
tSCC    zServer_Table_Id_Field_NAME[] = "SERVER_TABLE_ID_FIELD";
#define zNotServer_Table_Id_Field_Pfx NULL
#define zNotServer_Table_Id_Field_Name NULL
tSCC    zServer_Table_Id_Field_Name[]= "server-table-id-field";
tSCC    zServer_Table_Id_FieldDefaultArg[]= "id";
#define SERVER_TABLE_ID_FIELD_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Server_Table_Color_Field option description:
 */
tSCC    zServer_Table_Color_FieldText[] =
        "Name of the color-field in the servertable";
tSCC    zServer_Table_Color_Field_NAME[] = "SERVER_TABLE_COLOR_FIELD";
#define zNotServer_Table_Color_Field_Pfx NULL
#define zNotServer_Table_Color_Field_Name NULL
tSCC    zServer_Table_Color_Field_Name[]= "server-table-color-field";
tSCC    zServer_Table_Color_FieldDefaultArg[]= "color";
#define SERVER_TABLE_COLOR_FIELD_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Syslog option description:
 */
tSCC    zSyslogText[] =
        "Use syslog for runtime messages";
tSCC    zSyslog_NAME[]             = "SYSLOG";
#define zNotSyslog_Pfx               NULL
#define zNotSyslog_Name              NULL
tSCC    zSyslog_Name[]             = "syslog";
#define SYSLOG_FLAGS       (OPTST_BOOLEAN | OPTST_DISABLED | OPTST_INIT)

/*
 *  Stderr option description:
 */
tSCC    zStderrText[] =
        "Write non-debug messages to stderr";
tSCC    zStderr_NAME[]             = "STDERR";
#define zNotStderr_Pfx               NULL
#define zNotStderr_Name              NULL
tSCC    zStderr_Name[]             = "stderr";
#define STDERR_FLAGS       (OPTST_BOOLEAN | OPTST_DISABLED | OPTST_INIT)

/*
 *  Debug option description:
 */
tSCC    zDebugText[] =
        "Debug mode";
tSCC    zDebug_NAME[]              = "DEBUG";
#define zNotDebug_Pfx                NULL
#define zNotDebug_Name               NULL
tSCC    zDebug_Name[]              = "debug";
#define zDebugDefaultArg             ((tCC*)0)
#define DEBUG_FLAGS       (OPTST_NUMERIC | OPTST_DISABLED | OPTST_INIT)

/*
 *  Logfile option description:
 */
tSCC    zLogfileText[] =
        "Log messages to this file";
tSCC    zLogfile_NAME[]            = "LOGFILE";
#define zNotLogfile_Pfx              NULL
#define zNotLogfile_Name             NULL
tSCC    zLogfile_Name[]            = "logfile";
tSCC    zLogfileDefaultArg[]         = "/var/log/upwatch/upwatch.log";
#define LOGFILE_FLAGS       (OPTST_DISABLED | OPTST_INIT)

/*
 *  Help option description:
 */
tSCC zHelpText[]  = "Display usage information and exit";
tSCC zHelp_Name[] = "help";

/*
 *  More_Help option description:
 */
tSCC zMore_HelpText[]  = "Extended usage information passed thru pager";
tSCC zMore_Help_Name[] = "more-help";

/*
 *  Version option description:
 */
tSCC zVersionText[]    = "Output version information and exit";
tSCC zVersion_Name[]   = "version";

/*
 *  Save_Opts option description:
 */
tSCC zSave_OptsText[]  = "Save the option state to an rc file";
tSCC zSave_Opts_Name[] = "save-opts";

/*
 *  Load_Opts option description:
 */
extern tOptProc doLoadOpt;
tSCC    zLoad_OptsText[]     = "Load options from an rc file";
tSCC    zLoad_Opts_NAME[]    = "LOAD_OPTS";
tSCC    zNotLoad_Opts_Name[] = "no-load-opts";
tSCC    zNotLoad_Opts_Pfx[]  = "no";
#define zLoad_Opts_Name        (zNotLoad_Opts_Name + 3)
/*
 *  Procedures to call when option(s) are encountered
 */
static tOptProc doOptCompress;
static tOptProc doOptMulti_Value_Cache_Size;
static tOptProc doOptDebug;

/*
 *  These are always callable, whether
 *  TEST_UW_TNOT_OPTS is defined or not
 */
static tOptProc doUsageOpt;
extern  tOptProc  doVersion;
#define DOVERPROC doVersion
extern tOptProc doPagedUsage;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Uw_Tnot Option Descriptions.
 */
static tOptDesc optDesc[ OPTION_CT ] = {
  {  /* entry idx, value */ 0, VALUE_OPT_COMPRESS,
     /* equiv idx, value */ 0, VALUE_OPT_COMPRESS,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ COMPRESS_FLAGS,
     /* last opt argumnt */ (char*)zCompressDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptCompress,
     /* desc, NAME, name */ zCompressText,  zCompress_NAME,
                            zCompress_Name,
     /* disablement strs */ zNotCompress_Name, zNotCompress_Pfx },

  {  /* entry idx, value */ 1, VALUE_OPT_SPOOLDIR,
     /* equiv idx, value */ 1, VALUE_OPT_SPOOLDIR,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SPOOLDIR_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zSpooldirText,  zSpooldir_NAME,
                            zSpooldir_Name,
     /* disablement strs */ zNotSpooldir_Name, zNotSpooldir_Pfx },

  {  /* entry idx, value */ 2, VALUE_OPT_INPUT,
     /* equiv idx, value */ 2, VALUE_OPT_INPUT,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INPUT_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ stackOptArg,
     /* desc, NAME, name */ zInputText,  zInput_NAME,
                            zInput_Name,
     /* disablement strs */ zNotInput_Name, zNotInput_Pfx },

  {  /* entry idx, value */ 3, VALUE_OPT_OUTPUT,
     /* equiv idx, value */ 3, VALUE_OPT_OUTPUT,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OUTPUT_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ stackOptArg,
     /* desc, NAME, name */ zOutputText,  zOutput_NAME,
                            zOutput_Name,
     /* disablement strs */ zNotOutput_Name, zNotOutput_Pfx },

  {  /* entry idx, value */ 4, VALUE_OPT_FAILURES,
     /* equiv idx, value */ 4, VALUE_OPT_FAILURES,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FAILURES_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zFailuresText,  zFailures_NAME,
                            zFailures_Name,
     /* disablement strs */ zNotFailures_Name, zNotFailures_Pfx },

  {  /* entry idx, value */ 5, VALUE_OPT_NOTIFY,
     /* equiv idx, value */ 5, VALUE_OPT_NOTIFY,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NOTIFY_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ stackOptArg,
     /* desc, NAME, name */ zNotifyText,  zNotify_NAME,
                            zNotify_Name,
     /* disablement strs */ zNotNotify_Name, zNotNotify_Pfx },

  {  /* entry idx, value */ 6, VALUE_OPT_SMTPSERVER,
     /* equiv idx, value */ 6, VALUE_OPT_SMTPSERVER,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SMTPSERVER_FLAGS,
     /* last opt argumnt */ (char*)zSmtpserverDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zSmtpserverText,  zSmtpserver_NAME,
                            zSmtpserver_Name,
     /* disablement strs */ zNotSmtpserver_Name, zNotSmtpserver_Pfx },

  {  /* entry idx, value */ 7, VALUE_OPT_SMTPSERVERPORT,
     /* equiv idx, value */ 7, VALUE_OPT_SMTPSERVERPORT,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SMTPSERVERPORT_FLAGS,
     /* last opt argumnt */ (char*)zSmtpserverportDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ zSmtpserverportText,  zSmtpserverport_NAME,
                            zSmtpserverport_Name,
     /* disablement strs */ zNotSmtpserverport_Name, zNotSmtpserverport_Pfx },

  {  /* entry idx, value */ 8, VALUE_OPT_FROM_EMAIL,
     /* equiv idx, value */ 8, VALUE_OPT_FROM_EMAIL,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FROM_EMAIL_FLAGS,
     /* last opt argumnt */ (char*)zFrom_EmailDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zFrom_EmailText,  zFrom_Email_NAME,
                            zFrom_Email_Name,
     /* disablement strs */ zNotFrom_Email_Name, zNotFrom_Email_Pfx },

  {  /* entry idx, value */ 9, VALUE_OPT_FROM_NAME,
     /* equiv idx, value */ 9, VALUE_OPT_FROM_NAME,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FROM_NAME_FLAGS,
     /* last opt argumnt */ (char*)zFrom_NameDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zFrom_NameText,  zFrom_Name_NAME,
                            zFrom_Name_Name,
     /* disablement strs */ zNotFrom_Name_Name, zNotFrom_Name_Pfx },

  {  /* entry idx, value */ 10, VALUE_OPT_COPY,
     /* equiv idx, value */ 10, VALUE_OPT_COPY,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ COPY_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zCopyText,  zCopy_NAME,
                            zCopy_Name,
     /* disablement strs */ zNotCopy_Name, zNotCopy_Pfx },

  {  /* entry idx, value */ 11, VALUE_OPT_TRUST,
     /* equiv idx, value */ 11, VALUE_OPT_TRUST,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TRUST_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ stackOptArg,
     /* desc, NAME, name */ zTrustText,  zTrust_NAME,
                            zTrust_Name,
     /* disablement strs */ zNotTrust_Name, zNotTrust_Pfx },

  {  /* entry idx, value */ 12, VALUE_OPT_RUN_QUEUE,
     /* equiv idx, value */ 12, VALUE_OPT_RUN_QUEUE,
     /* option argument  */ ARG_NONE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ RUN_QUEUE_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zRun_QueueText,  zRun_Queue_NAME,
                            zRun_Queue_Name,
     /* disablement strs */ zNotRun_Queue_Name, zNotRun_Queue_Pfx },

  {  /* entry idx, value */ 13, VALUE_OPT_QUERY_SERVER_BY_NAME,
     /* equiv idx, value */ 13, VALUE_OPT_QUERY_SERVER_BY_NAME,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ QUERY_SERVER_BY_NAME_FLAGS,
     /* last opt argumnt */ (char*)zQuery_Server_By_NameDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zQuery_Server_By_NameText,  zQuery_Server_By_Name_NAME,
                            zQuery_Server_By_Name_Name,
     /* disablement strs */ zNotQuery_Server_By_Name_Name, zNotQuery_Server_By_Name_Pfx },

  {  /* entry idx, value */ 14, VALUE_OPT_QUERY_SERVER_BY_ID,
     /* equiv idx, value */ 14, VALUE_OPT_QUERY_SERVER_BY_ID,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ QUERY_SERVER_BY_ID_FLAGS,
     /* last opt argumnt */ (char*)zQuery_Server_By_IdDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zQuery_Server_By_IdText,  zQuery_Server_By_Id_NAME,
                            zQuery_Server_By_Id_Name,
     /* disablement strs */ zNotQuery_Server_By_Id_Name, zNotQuery_Server_By_Id_Pfx },

  {  /* entry idx, value */ 15, VALUE_OPT_QUERY_SERVER_BY_IP,
     /* equiv idx, value */ 15, VALUE_OPT_QUERY_SERVER_BY_IP,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ QUERY_SERVER_BY_IP_FLAGS,
     /* last opt argumnt */ (char*)zQuery_Server_By_IpDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zQuery_Server_By_IpText,  zQuery_Server_By_Ip_NAME,
                            zQuery_Server_By_Ip_Name,
     /* disablement strs */ zNotQuery_Server_By_Ip_Name, zNotQuery_Server_By_Ip_Pfx },

  {  /* entry idx, value */ 16, VALUE_OPT_SUMMARIZE,
     /* equiv idx, value */ 16, VALUE_OPT_SUMMARIZE,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SUMMARIZE_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zSummarizeText,  zSummarize_NAME,
                            zSummarize_Name,
     /* disablement strs */ zNotSummarize_Name, zNotSummarize_Pfx },

  {  /* entry idx, value */ 17, VALUE_OPT_MULTI_VALUE_INSERTS,
     /* equiv idx, value */ 17, VALUE_OPT_MULTI_VALUE_INSERTS,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MULTI_VALUE_INSERTS_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionBooleanVal,
     /* desc, NAME, name */ zMulti_Value_InsertsText,  zMulti_Value_Inserts_NAME,
                            zMulti_Value_Inserts_Name,
     /* disablement strs */ zNotMulti_Value_Inserts_Name, zNotMulti_Value_Inserts_Pfx },

  {  /* entry idx, value */ 18, VALUE_OPT_MULTI_VALUE_CACHE_SIZE,
     /* equiv idx, value */ 18, VALUE_OPT_MULTI_VALUE_CACHE_SIZE,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MULTI_VALUE_CACHE_SIZE_FLAGS,
     /* last opt argumnt */ (char*)zMulti_Value_Cache_SizeDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptMulti_Value_Cache_Size,
     /* desc, NAME, name */ zMulti_Value_Cache_SizeText,  zMulti_Value_Cache_Size_NAME,
                            zMulti_Value_Cache_Size_Name,
     /* disablement strs */ zNotMulti_Value_Cache_Size_Name, zNotMulti_Value_Cache_Size_Pfx },

  {  /* entry idx, value */ 19, VALUE_OPT_SLAVE,
     /* equiv idx, value */ 19, VALUE_OPT_SLAVE,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SLAVE_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zSlaveText,  zSlave_NAME,
                            zSlave_Name,
     /* disablement strs */ zNotSlave_Name, zNotSlave_Pfx },

  {  /* entry idx, value */ 20, VALUE_OPT_DBTYPE,
     /* equiv idx, value */ 20, VALUE_OPT_DBTYPE,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DBTYPE_FLAGS,
     /* last opt argumnt */ (char*)zDbtypeDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zDbtypeText,  zDbtype_NAME,
                            zDbtype_Name,
     /* disablement strs */ zNotDbtype_Name, zNotDbtype_Pfx },

  {  /* entry idx, value */ 21, VALUE_OPT_DBCOMPRESS,
     /* equiv idx, value */ 21, VALUE_OPT_DBCOMPRESS,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DBCOMPRESS_FLAGS,
     /* last opt argumnt */ (char*)zDbcompressDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ zDbcompressText,  zDbcompress_NAME,
                            zDbcompress_Name,
     /* disablement strs */ zNotDbcompress_Name, zNotDbcompress_Pfx },

  {  /* entry idx, value */ 22, VALUE_OPT_DBHOST,
     /* equiv idx, value */ 22, VALUE_OPT_DBHOST,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DBHOST_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zDbhostText,  zDbhost_NAME,
                            zDbhost_Name,
     /* disablement strs */ zNotDbhost_Name, zNotDbhost_Pfx },

  {  /* entry idx, value */ 23, VALUE_OPT_DBPORT,
     /* equiv idx, value */ 23, VALUE_OPT_DBPORT,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DBPORT_FLAGS,
     /* last opt argumnt */ (char*)zDbportDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionNumericVal,
     /* desc, NAME, name */ zDbportText,  zDbport_NAME,
                            zDbport_Name,
     /* disablement strs */ zNotDbport_Name, zNotDbport_Pfx },

  {  /* entry idx, value */ 24, VALUE_OPT_DBNAME,
     /* equiv idx, value */ 24, VALUE_OPT_DBNAME,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DBNAME_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zDbnameText,  zDbname_NAME,
                            zDbname_Name,
     /* disablement strs */ zNotDbname_Name, zNotDbname_Pfx },

  {  /* entry idx, value */ 25, VALUE_OPT_DBUSER,
     /* equiv idx, value */ 25, VALUE_OPT_DBUSER,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DBUSER_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zDbuserText,  zDbuser_NAME,
                            zDbuser_Name,
     /* disablement strs */ zNotDbuser_Name, zNotDbuser_Pfx },

  {  /* entry idx, value */ 26, VALUE_OPT_DBPASSWD,
     /* equiv idx, value */ 26, VALUE_OPT_DBPASSWD,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DBPASSWD_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zDbpasswdText,  zDbpasswd_NAME,
                            zDbpasswd_Name,
     /* disablement strs */ zNotDbpasswd_Name, zNotDbpasswd_Pfx },

  {  /* entry idx, value */ 27, VALUE_OPT_SERVER_TABLE_NAME,
     /* equiv idx, value */ 27, VALUE_OPT_SERVER_TABLE_NAME,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SERVER_TABLE_NAME_FLAGS,
     /* last opt argumnt */ (char*)zServer_Table_NameDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zServer_Table_NameText,  zServer_Table_Name_NAME,
                            zServer_Table_Name_Name,
     /* disablement strs */ zNotServer_Table_Name_Name, zNotServer_Table_Name_Pfx },

  {  /* entry idx, value */ 28, VALUE_OPT_SERVER_TABLE_NAME_FIELD,
     /* equiv idx, value */ 28, VALUE_OPT_SERVER_TABLE_NAME_FIELD,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SERVER_TABLE_NAME_FIELD_FLAGS,
     /* last opt argumnt */ (char*)zServer_Table_Name_FieldDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zServer_Table_Name_FieldText,  zServer_Table_Name_Field_NAME,
                            zServer_Table_Name_Field_Name,
     /* disablement strs */ zNotServer_Table_Name_Field_Name, zNotServer_Table_Name_Field_Pfx },

  {  /* entry idx, value */ 29, VALUE_OPT_SERVER_TABLE_ID_FIELD,
     /* equiv idx, value */ 29, VALUE_OPT_SERVER_TABLE_ID_FIELD,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SERVER_TABLE_ID_FIELD_FLAGS,
     /* last opt argumnt */ (char*)zServer_Table_Id_FieldDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zServer_Table_Id_FieldText,  zServer_Table_Id_Field_NAME,
                            zServer_Table_Id_Field_Name,
     /* disablement strs */ zNotServer_Table_Id_Field_Name, zNotServer_Table_Id_Field_Pfx },

  {  /* entry idx, value */ 30, VALUE_OPT_SERVER_TABLE_COLOR_FIELD,
     /* equiv idx, value */ 30, VALUE_OPT_SERVER_TABLE_COLOR_FIELD,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SERVER_TABLE_COLOR_FIELD_FLAGS,
     /* last opt argumnt */ (char*)zServer_Table_Color_FieldDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zServer_Table_Color_FieldText,  zServer_Table_Color_Field_NAME,
                            zServer_Table_Color_Field_Name,
     /* disablement strs */ zNotServer_Table_Color_Field_Name, zNotServer_Table_Color_Field_Pfx },

  {  /* entry idx, value */ 31, VALUE_OPT_SYSLOG,
     /* equiv idx, value */ 31, VALUE_OPT_SYSLOG,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SYSLOG_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionBooleanVal,
     /* desc, NAME, name */ zSyslogText,  zSyslog_NAME,
                            zSyslog_Name,
     /* disablement strs */ zNotSyslog_Name, zNotSyslog_Pfx },

  {  /* entry idx, value */ 32, VALUE_OPT_STDERR,
     /* equiv idx, value */ 32, VALUE_OPT_STDERR,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ STDERR_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionBooleanVal,
     /* desc, NAME, name */ zStderrText,  zStderr_NAME,
                            zStderr_Name,
     /* disablement strs */ zNotStderr_Name, zNotStderr_Pfx },

  {  /* entry idx, value */ 33, VALUE_OPT_DEBUG,
     /* equiv idx, value */ 33, VALUE_OPT_DEBUG,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DEBUG_FLAGS,
     /* last opt argumnt */ (char*)zDebugDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptDebug,
     /* desc, NAME, name */ zDebugText,  zDebug_NAME,
                            zDebug_Name,
     /* disablement strs */ zNotDebug_Name, zNotDebug_Pfx },

  {  /* entry idx, value */ 34, VALUE_OPT_LOGFILE,
     /* equiv idx, value */ 34, VALUE_OPT_LOGFILE,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOGFILE_FLAGS,
     /* last opt argumnt */ (char*)zLogfileDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zLogfileText,  zLogfile_NAME,
                            zLogfile_Name,
     /* disablement strs */ zNotLogfile_Name, zNotLogfile_Pfx },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* option argument  */ ARG_MAY,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max act ct  */ 0, 1, 0,
     /* opt state flags  */ OPTST_INIT,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ DOVERPROC,
     /* desc, NAME, name */ zVersionText, NULL, zVersion_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* option argument  */ ARG_NONE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max act ct  */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ zHelpText, NULL, zHelp_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* option argument  */ ARG_NONE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max act ct  */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ doPagedUsage,
     /* desc, NAME, name */ zMore_HelpText, NULL, zMore_Help_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_SAVE_OPTS, VALUE_OPT_SAVE_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* option argument  */ '?',
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max act ct  */ 0, 1, 0,
     /* opt state flags  */ OPTST_INIT,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zSave_OptsText, NULL, zSave_Opts_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_LOAD_OPTS, VALUE_OPT_LOAD_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ OPTST_DISABLE_IMM,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doLoadOpt,
     /* desc, NAME, name */ zLoad_OptsText, zLoad_Opts_NAME, zLoad_Opts_Name,
     /* disablement strs */ zNotLoad_Opts_Name, zNotLoad_Opts_Pfx }
};

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Uw_Tnot Option Environment
 */
tSCC   zPROGNAME[]   = "UW_TNOT";
tSCC   zUsageTitle[] =
"uw_tnot - Upwatch parallel probe daemon - Ver. 0.8\n\
USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]...\n";
tSCC   zRcName[]     = ".uw_tnotrc";
tSCC*  apzHomeList[] = {
       "/etc/upwatch.conf",
       "/etc/upwatch.d/uw_tnot.conf",
       "$HOME/.upwatchrc",
       "$HOME",
       "$$/upwatch.conf",
       "$$/uw_tnot.conf",
       NULL };

tSCC   zBugsAddr[]    = "info@upwatch.com";
tSCC   zExplain[]     = "\n\n";

tSCC    zDetail[]     = "\n\
uw_tnot reads probe resultfiles, and stores them in the database\n";

extern  tUsageProc optionUsage;

tSCC    zFullVersion[] = UW_TNOT_FULL_VERSION;

tOptions uw_tnotOptions = {
    OPTIONS_STRUCT_VERSION,
    NULL,         NULL,        zPROGNAME,
    zRcName,      zCopyright,  zCopyrightNotice,
    zFullVersion, apzHomeList, zUsageTitle,
    zExplain,     zDetail,     NULL,
    optionUsage,
    ( OPTPROC_NONE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_NO_ARGS ),
    0, NULL,
    { INDEX_OPT_MORE_HELP,
      INDEX_OPT_SAVE_OPTS,
      NO_EQUIVALENT /* no '-#' option */,
      NO_EQUIVALENT /* no default option */ },
    OPTION_CT, 35 /* user option count */,
    optDesc,
    0, (char**)NULL,  /* original argc + argv    */
    zBugsAddr         /* address to send bugs to */
};

/*
 *  Create the static procedure(s) declared above.
 */
static void
#ifdef __cplusplus
doUsageOpt(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
#else
doUsageOpt( pOpts, pOD )
    tOptions*  pOpts;
    tOptDesc*  pOD;
#endif
{
    USAGE( EXIT_SUCCESS );
}

/* * * * * * *
 *
 *   For the "Compress Option".
 */
static void
#ifdef __cplusplus
doOptCompress(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
#else
doOptCompress( pOptions, pOptDesc )
    tOptions*   pOptions;
    tOptDesc*   pOptDesc;
#endif
{
    static const struct {const int rmin, rmax;} rng[ 1 ] = {
        { 0, 9 } };
    int val, ix;
    tCC* pzIndent = "\t\t\t\t  ";
    extern FILE* option_usage_fp;

    if (pOptDesc == NULL) /* usage is requesting range list
                             option_usage_fp has already been set */
        goto emit_ranges;

    val = atoi( pOptDesc->pzLastArg );
    for (ix = 0; ix < 1; ix++) {
        if (val < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (val == rng[ix].rmin)
            goto valid_return;
        if (rng[ix].rmax == INT_MIN)
            continue;
        if (val <= rng[ix].rmax)
            goto valid_return;
    }

    option_usage_fp = stderr;
    fprintf( stderr, "%s error:  %s option value ``%s''is out of range.\n",
             pOptions->pzProgName, pOptDesc->pz_Name, pOptDesc->pzLastArg );
    pzIndent = "\t";

  emit_ranges:
    fprintf( option_usage_fp, "%sit must lie in the range: %d to %d\n",
             pzIndent, rng[0].rmin, rng[0].rmax );
    if (pOptDesc == NULL)
        return;

    USAGE( EXIT_FAILURE );
    /* NOTREACHED */

  valid_return:
    pOptDesc->pzLastArg = (char*)val;
}

/* * * * * * *
 *
 *   For the "Multi_Value_Cache_Size Option".
 */
static void
#ifdef __cplusplus
doOptMulti_Value_Cache_Size(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
#else
doOptMulti_Value_Cache_Size( pOptions, pOptDesc )
    tOptions*   pOptions;
    tOptDesc*   pOptDesc;
#endif
{
    static const struct {const int rmin, rmax;} rng[ 1 ] = {
        { 10, 1000 } };
    int val, ix;
    tCC* pzIndent = "\t\t\t\t  ";
    extern FILE* option_usage_fp;

    if (pOptDesc == NULL) /* usage is requesting range list
                             option_usage_fp has already been set */
        goto emit_ranges;

    val = atoi( pOptDesc->pzLastArg );
    for (ix = 0; ix < 1; ix++) {
        if (val < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (val == rng[ix].rmin)
            goto valid_return;
        if (rng[ix].rmax == INT_MIN)
            continue;
        if (val <= rng[ix].rmax)
            goto valid_return;
    }

    option_usage_fp = stderr;
    fprintf( stderr, "%s error:  %s option value ``%s''is out of range.\n",
             pOptions->pzProgName, pOptDesc->pz_Name, pOptDesc->pzLastArg );
    pzIndent = "\t";

  emit_ranges:
    fprintf( option_usage_fp, "%sit must lie in the range: %d to %d\n",
             pzIndent, rng[0].rmin, rng[0].rmax );
    if (pOptDesc == NULL)
        return;

    USAGE( EXIT_FAILURE );
    /* NOTREACHED */

  valid_return:
    pOptDesc->pzLastArg = (char*)val;
}

/* * * * * * *
 *
 *   For the "Debug Option".
 */
static void
#ifdef __cplusplus
doOptDebug(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
#else
doOptDebug( pOptions, pOptDesc )
    tOptions*   pOptions;
    tOptDesc*   pOptDesc;
#endif
{
    static const struct {const int rmin, rmax;} rng[ 1 ] = {
        { 0, 9 } };
    int val, ix;
    tCC* pzIndent = "\t\t\t\t  ";
    extern FILE* option_usage_fp;

    if (pOptDesc == NULL) /* usage is requesting range list
                             option_usage_fp has already been set */
        goto emit_ranges;

    val = atoi( pOptDesc->pzLastArg );
    for (ix = 0; ix < 1; ix++) {
        if (val < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (val == rng[ix].rmin)
            goto valid_return;
        if (rng[ix].rmax == INT_MIN)
            continue;
        if (val <= rng[ix].rmax)
            goto valid_return;
    }

    option_usage_fp = stderr;
    fprintf( stderr, "%s error:  %s option value ``%s''is out of range.\n",
             pOptions->pzProgName, pOptDesc->pz_Name, pOptDesc->pzLastArg );
    pzIndent = "\t";

  emit_ranges:
    fprintf( option_usage_fp, "%sit must lie in the range: %d to %d\n",
             pzIndent, rng[0].rmin, rng[0].rmax );
    if (pOptDesc == NULL)
        return;

    USAGE( EXIT_FAILURE );
    /* NOTREACHED */

  valid_return:
    pOptDesc->pzLastArg = (char*)val;
}

