/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (uw_tnot.h)
 *  
 *  It has been AutoGen-ed  Tuesday January  6, 2004 at 11:44:46 AM CET
 *  From the definitions    uw_tnot.def
 *  and the template file   options
 */
/*
 *  This file contains the programmatic interface to the Automated
 *  Options generated for the uw_tnot program.
 *  These macros are documented in the AutoGen info file in the
 *  "AutoOpts" chapter.  Please refer to that doc for usage help.
 */
#ifndef AUTOOPTS_UW_TNOT_H_GUARD
#define AUTOOPTS_UW_TNOT_H_GUARD

/*
 * uw_tnot copyright 2002 Upwatch BV - all rights reserved
 *
 * Redistribution Prohibited. Violation will be prosecuted to the maximum extent possible by applicable law.
 */
#include <options.h>

/*
 *  Enumeration of each option:
 */
typedef enum {
        INDEX_OPT_COMPRESS         =  0,
        INDEX_OPT_SPOOLDIR         =  1,
        INDEX_OPT_INPUT            =  2,
        INDEX_OPT_OUTPUT           =  3,
        INDEX_OPT_FAILURES         =  4,
        INDEX_OPT_NOTIFY           =  5,
        INDEX_OPT_SMTPSERVER       =  6,
        INDEX_OPT_SMTPSERVERPORT   =  7,
        INDEX_OPT_FROM_EMAIL       =  8,
        INDEX_OPT_FROM_NAME        =  9,
        INDEX_OPT_COPY             = 10,
        INDEX_OPT_TRUST            = 11,
        INDEX_OPT_RUN_QUEUE        = 12,
        INDEX_OPT_QUERY_SERVER_BY_NAME = 13,
        INDEX_OPT_QUERY_SERVER_BY_ID = 14,
        INDEX_OPT_QUERY_SERVER_BY_IP = 15,
        INDEX_OPT_SUMMARIZE        = 16,
        INDEX_OPT_MULTI_VALUE_INSERTS = 17,
        INDEX_OPT_MULTI_VALUE_CACHE_SIZE = 18,
        INDEX_OPT_SLAVE            = 19,
        INDEX_OPT_DBTYPE           = 20,
        INDEX_OPT_DBCOMPRESS       = 21,
        INDEX_OPT_DBHOST           = 22,
        INDEX_OPT_DBPORT           = 23,
        INDEX_OPT_DBNAME           = 24,
        INDEX_OPT_DBUSER           = 25,
        INDEX_OPT_DBPASSWD         = 26,
        INDEX_OPT_SERVER_TABLE_NAME = 27,
        INDEX_OPT_SERVER_TABLE_NAME_FIELD = 28,
        INDEX_OPT_SERVER_TABLE_ID_FIELD = 29,
        INDEX_OPT_SERVER_TABLE_COLOR_FIELD = 30,
        INDEX_OPT_SYSLOG           = 31,
        INDEX_OPT_STDERR           = 32,
        INDEX_OPT_DEBUG            = 33,
        INDEX_OPT_LOGFILE          = 34,
        INDEX_OPT_VERSION          = 35,
        INDEX_OPT_HELP             = 36,
        INDEX_OPT_MORE_HELP        = 37,
        INDEX_OPT_SAVE_OPTS        = 38,
        INDEX_OPT_LOAD_OPTS        = 39
} teOptIndex;

#define OPTION_CT    40
#define UW_TNOT_VERSION       "0.8"
#define UW_TNOT_FULL_VERSION  "uw_tnot - Upwatch parallel probe daemon - Ver. 0.8"

/*
 *  Interface defines for all options.  Replace "n" with
 *  the UPPER_CASED option name (as in the teOptIndex
 *  enumeration above).  e.g. HAVE_OPT( COMPRESS )
 */
#ifdef __STDC__
#  define       DESC(n) uw_tnotOptions.pOptDesc[INDEX_OPT_ ## n]
#else
#  define       DESC(n) uw_tnotOptions.pOptDesc[INDEX_OPT_/**/n]
#endif
#define     HAVE_OPT(n) (! UNUSED_OPT(& DESC(n)))
#define      OPT_ARG(n) (DESC(n).pzLastArg)
#define    STATE_OPT(n) (DESC(n).fOptState & OPTST_SET_MASK)
#define    COUNT_OPT(n) (DESC(n).optOccCt)
#define    ISSEL_OPT(n) (SELECTED_OPT(&DESC(n)))
#define ISUNUSED_OPT(n) (UNUSED_OPT(& DESC(n)))
#define  ENABLED_OPT(n) (! DISABLED_OPT(& DESC(n)))
#define  STACKCT_OPT(n) (((tArgList*)(DESC(n).optCookie))->useCt)
#define STACKLST_OPT(n) (((tArgList*)(DESC(n).optCookie))->apzArgs)
#define    CLEAR_OPT(n) STMTS( \
                DESC(n).fOptState &= OPTST_PERSISTENT;   \
                if ( (DESC(n).fOptState & OPTST_INITENABLED) == 0) \
                    DESC(n).fOptState |= OPTST_DISABLED; \
                DESC(n).optCookie = NULL )

/*
 *  Interface defines for specific options.
 */
#define VALUE_OPT_COMPRESS       'C'
#define OPT_VALUE_COMPRESS       (*(long*)(&OPT_ARG(COMPRESS)))
#define VALUE_OPT_SPOOLDIR       'S'
#define VALUE_OPT_INPUT          'I'
#define VALUE_OPT_OUTPUT         'O'
#define VALUE_OPT_FAILURES       'f'
#define VALUE_OPT_NOTIFY         'N'
#define VALUE_OPT_SMTPSERVER     6
#define VALUE_OPT_SMTPSERVERPORT 7
#define OPT_VALUE_SMTPSERVERPORT (*(long*)(&OPT_ARG(SMTPSERVERPORT)))
#define VALUE_OPT_FROM_EMAIL     8
#define VALUE_OPT_FROM_NAME      9
#define VALUE_OPT_COPY           'c'
#define VALUE_OPT_TRUST          't'
#define VALUE_OPT_RUN_QUEUE      'q'
#define VALUE_OPT_QUERY_SERVER_BY_NAME 13
#define VALUE_OPT_QUERY_SERVER_BY_ID 14
#define VALUE_OPT_QUERY_SERVER_BY_IP 15
#define VALUE_OPT_SUMMARIZE      16
#define VALUE_OPT_MULTI_VALUE_INSERTS 17
#define OPT_VALUE_MULTI_VALUE_INSERTS (*(ag_bool*)(&OPT_ARG(MULTI_VALUE_INSERTS)))
#define VALUE_OPT_MULTI_VALUE_CACHE_SIZE 18
#define OPT_VALUE_MULTI_VALUE_CACHE_SIZE (*(long*)(&OPT_ARG(MULTI_VALUE_CACHE_SIZE)))
#define VALUE_OPT_SLAVE          19
#define VALUE_OPT_DBTYPE         'T'
#define VALUE_OPT_DBCOMPRESS     'C'
#define OPT_VALUE_DBCOMPRESS     (*(long*)(&OPT_ARG(DBCOMPRESS)))
#define VALUE_OPT_DBHOST         'h'
#define VALUE_OPT_DBPORT         23
#define OPT_VALUE_DBPORT         (*(long*)(&OPT_ARG(DBPORT)))
#define VALUE_OPT_DBNAME         'n'
#define VALUE_OPT_DBUSER         'u'
#define VALUE_OPT_DBPASSWD       'p'
#define VALUE_OPT_SERVER_TABLE_NAME 27
#define VALUE_OPT_SERVER_TABLE_NAME_FIELD 28
#define VALUE_OPT_SERVER_TABLE_ID_FIELD 29
#define VALUE_OPT_SERVER_TABLE_COLOR_FIELD 30
#define VALUE_OPT_SYSLOG         's'
#define OPT_VALUE_SYSLOG         (*(ag_bool*)(&OPT_ARG(SYSLOG)))
#define VALUE_OPT_STDERR         'e'
#define OPT_VALUE_STDERR         (*(ag_bool*)(&OPT_ARG(STDERR)))
#define SET_OPT_STDERR(a)   STMTS( \
        DESC(STDERR).optActualIndex = 32; \
        DESC(STDERR).optActualValue = VALUE_OPT_STDERR; \
        DESC(STDERR).fOptState &= OPTST_PERSISTENT; \
        DESC(STDERR).fOptState |= OPTST_SET; \
        DESC(STDERR).pzLastArg  = (char*)(a); \
        (*(DESC(STDERR).pOptProc))( &uw_tnotOptions, \
                uw_tnotOptions.pOptDesc + 32 ) )
#define VALUE_OPT_DEBUG          'd'
#define OPT_VALUE_DEBUG          (*(long*)(&OPT_ARG(DEBUG)))
#define VALUE_OPT_LOGFILE        'l'

#define VALUE_OPT_VERSION        'v'
#define VALUE_OPT_SAVE_OPTS      '>'
#define VALUE_OPT_LOAD_OPTS      '<'
#define VALUE_OPT_HELP           '?'
#define VALUE_OPT_MORE_HELP      '!'
#define SET_OPT_SAVE_OPTS(a)   STMTS( \
        DESC(SAVE_OPTS).fOptState &= OPTST_PERSISTENT; \
        DESC(SAVE_OPTS).fOptState |= OPTST_SET; \
        DESC(SAVE_OPTS).pzLastArg  = (char*)(a) )

/*
 *  Interface defines not associated with particular options
 */
#define  ERRSKIP_OPTERR STMTS( uw_tnotOptions.fOptSet &= ~OPTPROC_ERRSTOP )
#define  ERRSTOP_OPTERR STMTS( uw_tnotOptions.fOptSet |= OPTPROC_ERRSTOP )
#define  RESTART_OPT(n) STMTS( \
                uw_tnotOptions.curOptIdx = (n); \
                uw_tnotOptions.pzCurOpt  = NULL )
#define    START_OPT    RESTART_OPT(1)
#define     USAGE(c)    (*uw_tnotOptions.pUsageProc)( &uw_tnotOptions, c )

/* * * * * *
 *
 *  Declare the uw_tnot option descriptor.
 */
#ifdef  __cplusplus
extern "C" {
#endif

extern tOptions   uw_tnotOptions;

/* * * * * *
 *
 *  Globals exported from the Upwatch parallel probe daemon option definitions
 */
#define progOptions uw_tnotOptions

#include <config.h>

#include <limits.h>

#include <stdio.h>

#include <stdlib.h>

#ifdef  __cplusplus
}
#endif
#endif /* AUTOOPTS_UW_TNOT_H_GUARD */
