/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (uwq_options.c)
 *  
 *  It has been AutoGen-ed  Thursday May 20, 2004 at 05:45:10 PM CEST
 *  From the definitions    uwq_options.def
 *  and the template file   options
 */
#include <stdio.h>
#include <limits.h>
#include "uwq_options.h"

#ifdef  __cplusplus
extern "C" {
#endif
tSCC zCopyright[] =
       "uwq copyright (c) 2002 Upwatch BV, all rights reserved";
tSCC zCopyrightNotice[] =
       "Redistribution Prohibited. Violation will be prosecuted to the maximum extent possible by applicable law.";
extern tOptProc doVersionStderr, doVersion, doPagedUsage, doLoadOpt;
static tOptProc doUsageOpt, doOptDebug;
extern tUsageProc optionUsage;

#ifndef NULL
#  define NULL 0
#endif
#ifndef EXIT_SUCCESS
#  define  EXIT_SUCCESS 0
#endif
#ifndef EXIT_FAILURE
#  define  EXIT_FAILURE 1
#endif
/*
 *  Spooldir option description:
 */
tSCC    zSpooldirText[] =
        "maildir-type spooldirectory for result files";
tSCC    zSpooldir_NAME[]           = "SPOOLDIR";
#define zNotSpooldir_Pfx             NULL
#define zNotSpooldir_Name            NULL
tSCC    zSpooldir_Name[]           = "spooldir";
#define SPOOLDIR_FLAGS       (OPTST_DISABLED)

/*
 *  No_Stat option description:
 */
tSCC    zNo_StatText[] =
        "Don't stat() every file for date/time";
tSCC    zNo_Stat_NAME[]            = "NO_STAT";
#define zNotNo_Stat_Pfx              NULL
#define zNotNo_Stat_Name             NULL
tSCC    zNo_Stat_Name[]            = "no-stat";
#define NO_STAT_FLAGS       (OPTST_BOOLEAN | OPTST_DISABLED)

/*
 *  Syslog option description:
 */
tSCC    zSyslogText[] =
        "Use syslog for runtime messages";
tSCC    zSyslog_NAME[]             = "SYSLOG";
#define zNotSyslog_Pfx               NULL
#define zNotSyslog_Name              NULL
tSCC    zSyslog_Name[]             = "syslog";
#define SYSLOG_FLAGS       (OPTST_BOOLEAN | OPTST_DISABLED)

/*
 *  Stderr option description:
 */
tSCC    zStderrText[] =
        "Write non-debug messages to stderr";
tSCC    zStderr_NAME[]             = "STDERR";
#define zNotStderr_Pfx               NULL
#define zNotStderr_Name              NULL
tSCC    zStderr_Name[]             = "stderr";
#define STDERR_FLAGS       (OPTST_BOOLEAN | OPTST_DISABLED)

/*
 *  Debug option description:
 */
tSCC    zDebugText[] =
        "Debug mode";
tSCC    zDebug_NAME[]              = "DEBUG";
#define zNotDebug_Pfx                NULL
#define zNotDebug_Name               NULL
tSCC    zDebug_Name[]              = "debug";
#define zDebugDefaultArg             ((tCC*)0)
#define DEBUG_FLAGS       (OPTST_NUMERIC | OPTST_DISABLED)

/*
 *  Logfile option description:
 */
tSCC    zLogfileText[] =
        "Log messages to this file";
tSCC    zLogfile_NAME[]            = "LOGFILE";
#define zNotLogfile_Pfx              NULL
#define zNotLogfile_Name             NULL
tSCC    zLogfile_Name[]            = "logfile";
tSCC    zLogfileDefaultArg[]         = "/var/log/upwatch/upwatch.log";
#define LOGFILE_FLAGS       (OPTST_DISABLED)

/*
 *  Help option description:
 */
tSCC zHelpText[]  = "Display usage information and exit";
tSCC zHelp_Name[] = "help";

/*
 *  More_Help option description:
 */
tSCC zMore_HelpText[]  = "Extended usage information passed thru pager";
tSCC zMore_Help_Name[] = "more-help";

/*
 *  Version option description:
 */
tSCC zVersionText[]    = "Output version information and exit";
tSCC zVersion_Name[]   = "version";

/*
 *  Save_Opts option description:
 */
tSCC zSave_OptsText[]  = "Save the option state to an rc file";
tSCC zSave_Opts_Name[] = "save-opts";

/*
 *  Load_Opts option description:
 */
tSCC    zLoad_OptsText[]     = "Load options from an rc file";
tSCC    zLoad_Opts_NAME[]    = "LOAD_OPTS";
tSCC    zNotLoad_Opts_Name[] = "no-load-opts";
tSCC    zNotLoad_Opts_Pfx[]  = "no";
#define zLoad_Opts_Name        (zNotLoad_Opts_Name + 3)

#define DOVERPROC doVersion

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Uwq Option Descriptions.
 */
static tOptDesc optDesc[ OPTION_CT ] = {
  {  /* entry idx, value */ 0, VALUE_OPT_SPOOLDIR,
     /* equiv idx, value */ 0, VALUE_OPT_SPOOLDIR,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SPOOLDIR_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zSpooldirText,  zSpooldir_NAME,
                            zSpooldir_Name,
     /* disablement strs */ zNotSpooldir_Name, zNotSpooldir_Pfx },

  {  /* entry idx, value */ 1, VALUE_OPT_NO_STAT,
     /* equiv idx, value */ 1, VALUE_OPT_NO_STAT,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NO_STAT_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionBooleanVal,
     /* desc, NAME, name */ zNo_StatText,  zNo_Stat_NAME,
                            zNo_Stat_Name,
     /* disablement strs */ zNotNo_Stat_Name, zNotNo_Stat_Pfx },

  {  /* entry idx, value */ 2, VALUE_OPT_SYSLOG,
     /* equiv idx, value */ 2, VALUE_OPT_SYSLOG,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SYSLOG_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionBooleanVal,
     /* desc, NAME, name */ zSyslogText,  zSyslog_NAME,
                            zSyslog_Name,
     /* disablement strs */ zNotSyslog_Name, zNotSyslog_Pfx },

  {  /* entry idx, value */ 3, VALUE_OPT_STDERR,
     /* equiv idx, value */ 3, VALUE_OPT_STDERR,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ STDERR_FLAGS,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionBooleanVal,
     /* desc, NAME, name */ zStderrText,  zStderr_NAME,
                            zStderr_Name,
     /* disablement strs */ zNotStderr_Name, zNotStderr_Pfx },

  {  /* entry idx, value */ 4, VALUE_OPT_DEBUG,
     /* equiv idx, value */ 4, VALUE_OPT_DEBUG,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DEBUG_FLAGS,
     /* last opt argumnt */ (char*)zDebugDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptDebug,
     /* desc, NAME, name */ zDebugText,  zDebug_NAME,
                            zDebug_Name,
     /* disablement strs */ zNotDebug_Name, zNotDebug_Pfx },

  {  /* entry idx, value */ 5, VALUE_OPT_LOGFILE,
     /* equiv idx, value */ 5, VALUE_OPT_LOGFILE,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOGFILE_FLAGS,
     /* last opt argumnt */ (char*)zLogfileDefaultArg,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zLogfileText,  zLogfile_NAME,
                            zLogfile_Name,
     /* disablement strs */ zNotLogfile_Name, zNotLogfile_Pfx },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* option argument  */ ARG_MAY,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max act ct  */ 0, 1, 0,
     /* opt state flags  */ OPTST_INIT,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ DOVERPROC,
     /* desc, NAME, name */ zVersionText, NULL, zVersion_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* option argument  */ ARG_NONE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max act ct  */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ zHelpText, NULL, zHelp_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* option argument  */ ARG_NONE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max act ct  */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ doPagedUsage,
     /* desc, NAME, name */ zMore_HelpText, NULL, zMore_Help_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_SAVE_OPTS, VALUE_OPT_SAVE_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* option argument  */ '?',
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max act ct  */ 0, 1, 0,
     /* opt state flags  */ OPTST_INIT,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zSave_OptsText, NULL, zSave_Opts_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_LOAD_OPTS, VALUE_OPT_LOAD_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* option argument  */ ARG_MUST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ OPTST_DISABLE_IMM,
     /* last opt argumnt */ NULL,
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doLoadOpt,
     /* desc, NAME, name */ zLoad_OptsText, zLoad_Opts_NAME, zLoad_Opts_Name,
     /* disablement strs */ zNotLoad_Opts_Name, zNotLoad_Opts_Pfx }
};

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Uwq Option Environment
 */
tSCC   zPROGNAME[]   = "UWQ";
tSCC   zUsageTitle[] =
"uwq - print a list of upwatch queue statuses - Ver. 0.95\n\
USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [string]\n";
tSCC   zRcName[]     = ".uwqrc";
tSCC*  apzHomeList[] = {
       "/etc/upwatch.conf",
       "$HOME/.upwatchrc",
       "$$/upwatch.conf",
       NULL };

tSCC   zBugsAddr[]    = "info@upwatch.com";
tSCC   zExplain[]     = "\n\n";
tSCC    zDetail[]     = "\n\
This utility lists an overview of the status of the queues\n";
tSCC    zFullVersion[] = UWQ_FULL_VERSION;

tOptions uwqOptions = {
    OPTIONS_STRUCT_VERSION,
    NULL,           NULL,           zPROGNAME,
    zRcName,        zCopyright,     zCopyrightNotice,
    zFullVersion,   apzHomeList,    zUsageTitle,
    zExplain,       zDetail,        NULL,           optionUsage,
    ( OPTPROC_NONE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_GNUUSAGE ),
    0, NULL,
    { INDEX_OPT_MORE_HELP,
      INDEX_OPT_SAVE_OPTS,
      NO_EQUIVALENT /* no '-#' option */,
      NO_EQUIVALENT /* no default option */ },
    OPTION_CT, 6 /* user option count */,
    optDesc,
    0, (char**)NULL,  /* original argc + argv    */
    zBugsAddr         /* address to send bugs to */
};

/*
 *  Create the static procedure(s) declared above.
 */
static void
doUsageOpt(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
{
    USAGE( EXIT_SUCCESS );
}

/* * * * * * *
 *
 *   For the "Debug Option".
 */
static void
doOptDebug(
    tOptions*   pOptions,
    tOptDesc*   pOptDesc )
{
    static const struct {const int rmin, rmax;} rng[ 1 ] = {
        { 0, 9 } };
    int val, ix;
    tCC* pzIndent = "\t\t\t\t  ";
    extern FILE* option_usage_fp;

    if (pOptDesc == NULL) /* usage is requesting range list
                             option_usage_fp has already been set */
        goto emit_ranges;

    val = atoi( pOptDesc->pzLastArg );
    for (ix = 0; ix < 1; ix++) {
        if (val < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (val == rng[ix].rmin)
            goto valid_return;
        if (rng[ix].rmax == INT_MIN)
            continue;
        if (val <= rng[ix].rmax)
            goto valid_return;
    }

    option_usage_fp = stderr;
    fprintf( stderr, "%s error:  %s option value ``%s''is out of range.\n",
             pOptions->pzProgName, pOptDesc->pz_Name, pOptDesc->pzLastArg );
    pzIndent = "\t";

  emit_ranges:
    fprintf( option_usage_fp, "%sit must lie in the range: %d to %d\n",
             pzIndent, rng[0].rmin, rng[0].rmax );
    if (pOptDesc == NULL)
        return;

    USAGE( EXIT_FAILURE );
    /* NOTREACHED */
    return;

  valid_return:
    pOptDesc->pzLastArg = (char*)val;
}

#ifdef  __cplusplus
}
#endif
