#! /bin/sh

# patch libstatgrab
pushd libstatgrab-0.7
if [ ! -f libstatgrab-cygwin.patch ]
then
  cp ../patches/libstatgrab-cygwin.patch .
  patch -p1 < libstatgrab-cygwin.patch
  cp ../patches/libstatgrab-configure.gnu .
  autoconf
fi
popd

aclocal \
&& autoheader \
&& libtoolize \
&& automake --gnu --add-missing \
&& autoconf
