#! /bin/sh
set -x

# libstatgrab
cd libstatgrab
#if [ ! -f libstatgrab-openbsd.patch ]
#then
#  cp ../patches/libstatgrab-openbsd.patch .
#  patch -p1 < libstatgrab-openbsd.patch
  aclocal
  libtoolize
  autoconf
  automake --gnu --add-missing
#fi
cd ..

aclocal \
&& autoheader \
&& libtoolize \
&& autoconf \
&& automake --gnu --add-missing 

cd xmbmon203
autoconf
cd ..

