#! /bin/sh

# libstatgrab
pushd libstatgrab-0.7
if [ ! -f libstatgrab-configure.gnu ]
then
  cp ../patches/libstatgrab-configure.gnu .
  autoconf
fi
popd

aclocal \
&& autoheader \
&& libtoolize \
&& automake --gnu --add-missing \
&& autoconf
